name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Tests
      run: |
        yarn
        yarn dlx ng lint
        yarn test:ci
        yarn e2e:ci
        yarn dlx codecov
